---

- name: ensure logwatch is installed
  apt:
    name: "{{ item }}"
    state: present 
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items:
    - logwatch

- name: configure logwatch
  template:
    src: logwatch.conf.j2
    dest: /etc/logwatch/conf/logwatch.conf
    owner: root
    group: root
    mode: 0644
  become: true